# Generated by Django 4.1.1 on 2022-09-23 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_post_media_alter_comentario_comentario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='media',
        ),
    ]
